FROM golang:alpine AS builder
WORKDIR /app
COPY backend/ ./
RUN apk add build-base && apk cache clean
ENV CGO_ENABLED=1
RUN go build -o ./colonel ./cmd/agent/main.go


FROM alpine
WORKDIR /app
COPY --from=builder /app/colonel ./colonel
EXPOSE 8090
CMD ["./colonel"]